name: Azure Enterprise ACME
trigger:
  batch: "true"
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts (1)'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: environment_components
    type: object
    default:
      - stage: 'dcd_cft_sandbox'
        environment: 'sbox'
        product: 'cft-platform'
        dependsOn: 'Precheck'
      # - stage: 'dcd_cftappsdata_demo'
      #   environment: 'sbox'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftappsdata-demo'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_demo'
      #   environment: 'sbox'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-demo'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_dev'
      #   environment: 'sbox'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-dev'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_ithc'
      #   environment: 'ithc'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-ithc'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_prod'
      #   environment: 'prod'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-prod'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_sbox'
      #   environment: 'sbox'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-sbox'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_stg'
      #   environment: 'stg'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-stg'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cftapps_test'
      #   environment: 'test'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cftapps-test'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cft_idam_dev'
      #   environment: 'dev'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cft-idam-dev'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cft_vh_pilot'
      #   environment: ''
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cft-vh-pilot'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cnp_dev'
      #   environment: 'dev'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cnp-dev'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cnp_prod'
      #   environment: 'prod'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cnp-prod'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dcd_cnp_qa'
      #   environment: 'dev'
      #   product: 'cft-platform'
      #   service_connection: 'dcd-cnp-qa'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_cftptl_intsvc'
      #   environment: 'ptl'
      #   product: 'cft-platform'
      #   service_connection: 'dts-cftptl-intsvc'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_cftsbox_intsvc'
      #   environment: 'sbox'
      #   product: 'cft-platform'
      #   service_connection: 'dts-cftsbox-intsvc'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_demo'
      #   environment: 'demo'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-demo'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_dev'
      #   environment: 'dev'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-dev'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_ithc'
      #   environment: 'ithc'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-ithc'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_prod'
      #   environment: 'prod'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-prod'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservicesptl'
      #   environment: 'ptl'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservicesptl'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservicesptl_sbox'
      #   environment: 'ptlsbox'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservicesptl-sbox'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_sbox'
      #   environment: 'sbox'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-sbox'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_stg'
      #   environment: 'stg'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-stg'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'dts_sharedservices_test'
      #   environment: 'test'
      #   product: 'sds-platform'
      #   service_connection: 'dts-sharedservices-test'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_hub_dev'
      #   environment: 'dev'
      #   product: 'hub'
      #   service_connection: 'hmcts-hub-dev'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_hub_prod_intsvc'
      #   environment: 'prod'
      #   product: 'hub'
      #   service_connection: 'hmcts-hub-prod-intsvc'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_hub_sbox'
      #   environment: 'sbox'
      #   product: 'hub'
      #   service_connection: 'hmcts-hub-sbox'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_hub_sbox_intsvc'
      #   environment: 'sbox'
      #   product: 'hub'
      #   service_connection: 'hmcts-hub-sbox-intsvc'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_hub_test'
      #   environment: 'test'
      #   product: 'hub'
      #   service_connection: 'hmcts-hub-test'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_soc_prod'
      #   environment: 'prod'
      #   product: 'soc'
      #   service_connection: 'hmcts-soc-prod'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'hmcts_soc_sbox'
      #   environment: 'sbox'
      #   product: 'soc'
      #   service_connection: 'hmcts-soc-sbox'
      #   dependsOn: 'dcd_cft_sandbox'
      # - stage: 'reform_cft_vh_dev'
      #   environment: 'dev'
      #   product: 'cft-platform'
      #   service_connection: 'reform-cft-vh-dev'
      #   dependsOn: 'dcd_cft_sandbox'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
  - name: init_subscription
    value: '04d27a32-7a07-48b3-95b8-3c8691e1a263'
  - name: component
    value: acme
  - name: service_connection
    value: $[replace($(System.StageName), "_", "-")]


stages:
  - stage: Precheck
    jobs:
      - job: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFT-Sandbox'

  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.stage }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job: TerraformPlanApply
            pool:
              vmImage: ${{ variables.agentPool }}
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.overrideAction }}
                  environment: ${{ deployment.environment }}
                  component: ${{ variables.component }}
                  # serviceConnection: ${{ deployment.service_connection }}
                  serviceConnection: ${{ variables.service_connection }}
                  terraformInitSubscription: ${{ variables.init_subscription }}
                  product: ${{ deployment.product }}
