name: Azure Enterprise ACME
trigger:
  batch: "true"
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts (1)'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: environment_components
    type: object
    default:
      - stage: 'dcd_cft_sandbox'
        service_connection: 'dcd-cft-sandbox'
      - stage: 'dcd_cftappsdata_demo'
        service_connection: 'dcd-cftappsdata-demo'
      - stage: 'dcd_cftapps_demo'
        service_connection: 'dcd-cftapps-demo'
      - stage: 'dcd_cftapps_dev'
        service_connection: 'dcd-cftapps-dev' 
      - stage: 'dcd_cftapps_ithc'
        service_connection: 'dcd-cftapps-ithc' 
      - stage: 'dcd_cftapps_prod'
        service_connection: 'dcd-cftapps-prod' 
      - stage: 'dcd_cftapps_sbox'
        service_connection: 'dcd-cftapps-sbox' 
      - stage: 'dcd_cftapps_stg'
        service_connection: 'dcd-cftapps-stg'
      - stage: 'dcd_cftapps_test'
        service_connection: 'dcd-cftapps-test'     
      - stage: 'dcd_cft_idam_dev'
        service_connection: 'dcd-cft-idam-dev' 
      - stage: 'dcd_cft_vh_pilot'
        service_connection: 'dcd-cft-vh-pilot' 
      - stage: 'dcd_cnp_dev'
        service_connection: 'dcd-cnp-dev' 
      - stage: 'dcd_cnp_prod'
        service_connection: 'dcd-cnp-prod' 
      - stage: 'dcd_cnp_qa'
        service_connection: 'dcd-cnp-qa' 
      - stage: 'dts_cftptl_intsvc'
        service_connection: 'dts-cftptl-intsvc' 
      - stage: 'dts_cftsbox_intsvc'
        service_connection: 'dts-cftsbox-intsvc'
      - stage: 'dts_sharedservices_demo'
        service_connection: 'dts-sharedservices-demo'
      - stage: 'dts_sharedservices_dev'
        service_connection: 'dts-sharedservices-dev' 
      - stage: 'dts_sharedservices_ithc'
        service_connection: 'dts-sharedservices-ithc' 
      - stage: 'dts_sharedservices_prod'
        service_connection: 'dts-sharedservices-prod' 
      - stage: 'dts_sharedservicesptl'
        service_connection: 'dts-sharedservicesptl' 
      - stage: 'dts_sharedservicesptl_sbox'
        service_connection: 'dts-sharedservicesptl-sbox' 
      - stage: 'dts_sharedservices_sbox'
        service_connection: 'dts-sharedservices-sbox' 
      - stage: 'dts_sharedservices_stg'
        service_connection: 'dts-sharedservices-stg' 
      - stage: 'dts_sharedservices_test'
        service_connection: 'dts-sharedservices-test'
      - stage: 'hmcts_hub_dev' 
        service_connection: 'hmcts-hub-dev'
      - stage: 'hmcts_hub_prod_intsvc'
        service_connection: 'hmcts-hub-prod-intsvc' 
      - stage: 'hmcts_hub_sbox'
        service_connection: 'hmcts-hub-sbox' 
      - stage: 'hmcts_hub_sbox_intsvc'
        service_connection: 'hmcts-hub-sbox-intsvc' 
      - stage: 'hmcts_hub_test'
        service_connection: 'hmcts-hub-test' 
      - stage: 'hmcts_soc_prod'
        service_connection: 'hmcts-soc-prod' 
      - stage: 'hmcts_soc_sbox'
        service_connection: 'hmcts-soc-sbox' 
      - stage: 'reform_cft_vh_dev'
        service_connection: 'reform-cft-vh-dev'
      - stage: 'dts_archiving_test'
        service_connection: 'DTS-ARCHIVING-TEST'
        subscription_id: 'cad00ede-36df-4e04-ad0b-d34a1e94ef76'
      - stage: 'dts_archiving_prod'
        service_connection: 'DTS-ARCHIVING-PROD'
        subscription_id: '61432c17-4377-4780-be02-d56e56ef2b07'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
  - name: init_subscription
    value: '04d27a32-7a07-48b3-95b8-3c8691e1a263'
  - name: component
    value: acme


stages:
  - stage: Precheck
    jobs:
      - job: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFT-Sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
      - stage: "${{ deployment.stage }}_acme"
        dependsOn: 'Precheck'
        jobs:
          - job: TerraformPlanApply
            pool:
              vmImage: ${{ variables.agentPool }}
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.overrideAction }}
                  ${{ if contains(deployment.stage, 'demo') }}:
                    environment: 'demo'
                  ${{ if contains(deployment.stage, 'dev') }}:
                    environment: 'dev'
                  ${{ if contains(deployment.stage, 'qa') }}:
                    environment: 'test'
                  ${{ if contains(deployment.stage, 'ithc') }}:
                    environment: 'ithc'
                  ${{ if and(contains(deployment.stage, 'ptl'), not(contains(deployment.stage, 'ptl_sbox'))) }}:
                    environment: 'ptl'
                  ${{ if contains(deployment.stage, 'ptl_sbox') }}:
                    environment: 'ptlsbox'
                  ${{ if contains(deployment.stage, 'prod') }}:
                    environment: 'prod'
                  ${{ if contains(deployment.stage, 'pilot') }}:
                    environment: 'prod'                  
                  ${{ if and(contains(deployment.stage, 'sbox'), not(contains(deployment.stage, 'ptl_sbox'))) }}:
                    environment: 'sbox'
                  ${{ if contains(deployment.stage, 'sandbox') }}:
                    environment: 'sbox'
                  ${{ if contains(deployment.stage, 'stg') }}:
                    environment: 'stg'
                  ${{ if contains(deployment.stage, 'test') }}:
                    environment: 'test'
                  component: ${{ variables.component }}
                  serviceConnection: ${{ deployment.service_connection }}
                  terraformInitSubscription: ${{ variables.init_subscription }}
                  stage: ${{ deployment.stage }}
                  ${{ if contains(deployment.stage, 'cft') }}:
                    product: 'cft-platform'
                  ${{ if contains(deployment.stage, 'cnp') }}:
                    product: 'cft-platform'
                  ${{ if contains(deployment.stage, 'sharedservices') }}:
                    product: 'sds-platform'
                  ${{ if contains(deployment.stage, 'hub') }}:
                    product: 'hub'
                  ${{ if contains(deployment.stage, 'soc') }}:
                    product: 'soc'
                  ${{ if contains(deployment.stage, 'archiving') }}:
                    product: 'arm'
                  ${{ if ne(deployment.subscription_id, '') }}:
                    planCommandOptions:
                      -var subscription_id=${{ deployment.subscription_id }}
